FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./bot /app/bot
COPY bot-entrypoint.sh /app/
RUN chmod +x /app/bot-entrypoint.sh

ENTRYPOINT ["/app/bot-entrypoint.sh"]