services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - api
